<?php

namespace AppBundle\Repository;

/**
 * SuprategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuprategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
